version: "1.0"
info:
  model: int-scaffold
packages:
- name: Meer1601GitProjectProject
  gitServerName: Meer_GH1
  gitUrl: https://github.com/Meer-Arfath-IBM
  gitUsername: Meer-Arfath-IBM
  gitBranch: main
